# Generated by Django 4.2.11 on 2024-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventplannerdb", "0002_speaker_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="contactNumber",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="speaker",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="website",
            field=models.URLField(default=""),
        ),
    ]
