# Generated by Django 4.2.11 on 2024-03-11 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventplannerdb", "0004_remove_sponsor_logo_speaker_icon_sponsor_companylogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registered_users",
            field=models.ManyToManyField(blank=True, related_name="registered_events", to=settings.AUTH_USER_MODEL),
        ),
    ]
