# Generated by Django 4.2.11 on 2024-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventplannerdb", "0006_event_checkedin_users_delete_usercheckin"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
