# Generated by Django 4.2.11 on 2024-03-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventplannerdb", "0007_event_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agenda", to="eventplannerdb.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "response",
                    models.IntegerField(
                        choices=[
                            (1, "Not Satisfied"),
                            (2, "Somewhat Satisfied"),
                            (3, "Neutral"),
                            (4, "Satisfied"),
                            (5, "Very Satisfied"),
                        ]
                    ),
                ),
                (
                    "survey_question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eventplannerdb.surveyquestion"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="user_response",
        ),
        migrations.AddField(
            model_name="survey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="is_anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="methodology",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="survey",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="surveys", to="eventplannerdb.event"
            ),
        ),
        migrations.DeleteModel(
            name="EventAgenda",
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="eventplannerdb.survey"
            ),
        ),
    ]
