# Generated by Django 4.2.11 on 2024-03-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventplannerdb", "0008_agenda_surveyquestion_surveyresponse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="checkedIn_users",
        ),
    ]
