# Generated by Django 4.2.11 on 2024-03-12 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventplannerdb", "0009_remove_event_checkedin_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checkin_time", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="eventplannerdb.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="checkedIn_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkedIn_events",
                through="eventplannerdb.CheckIn",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
